"""initial schema with versioning and agent audit

Revision ID: 256806e9ef93
Revises: 
Create Date: 2026-07-01 13:23:51.466696
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '256806e9ef93'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('universities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('website_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('universities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_universities_id'), ['id'], unique=False)

    op.create_table('agent_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('university_id', sa.Integer(), nullable=True),
    sa.Column('run_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('metrics_json', sa.JSON(), nullable=True),
    sa.Column('error_text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_runs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_runs_university_id'), ['university_id'], unique=False)

    op.create_table('programs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('university_id', sa.Integer(), nullable=True),
    sa.Column('faculty', sa.String(), nullable=True),
    sa.Column('program_name', sa.String(), nullable=False),
    sa.Column('degree', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('tuition_fee', sa.String(), nullable=True),
    sa.Column('requirements', sa.Text(), nullable=True),
    sa.Column('application_deadline', sa.String(), nullable=True),
    sa.Column('gpa_requirement', sa.String(), nullable=True),
    sa.Column('documents_required', sa.Text(), nullable=True),
    sa.Column('extracted_at', sa.DateTime(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('field_confidence', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('current_version_id', sa.Integer(), nullable=True),
    sa.Column('content_hash', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('programs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_programs_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_programs_id'), ['id'], unique=False)
        batch_op.create_index('ix_programs_uni_name_degree', ['university_id', 'program_name', 'degree'], unique=False)

    op.create_table('scraped_pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('university_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('raw_html', sa.Text(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scraped_pages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scraped_pages_id'), ['id'], unique=False)

    op.create_table('agent_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('agent_name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('input_summary', sa.Text(), nullable=True),
    sa.Column('output_summary', sa.Text(), nullable=True),
    sa.Column('log_text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_steps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_steps_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_steps_run_id'), ['run_id'], unique=False)

    op.create_table('change_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=True),
    sa.Column('university_id', sa.Integer(), nullable=True),
    sa.Column('field_name', sa.String(), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('change_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_change_logs_id'), ['id'], unique=False)

    op.create_table('program_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=True),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('faculty', sa.String(), nullable=True),
    sa.Column('program_name', sa.String(), nullable=False),
    sa.Column('degree', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('tuition_fee', sa.String(), nullable=True),
    sa.Column('requirements', sa.Text(), nullable=True),
    sa.Column('application_deadline', sa.String(), nullable=True),
    sa.Column('gpa_requirement', sa.String(), nullable=True),
    sa.Column('documents_required', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('field_confidence', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('valid_from', sa.DateTime(), nullable=True),
    sa.Column('valid_to', sa.DateTime(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('program_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_program_versions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_program_versions_is_current'), ['is_current'], unique=False)
        batch_op.create_index('ix_program_versions_prog_current', ['program_id', 'is_current'], unique=False)
        batch_op.create_index(batch_op.f('ix_program_versions_program_id'), ['program_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('program_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_program_versions_program_id'))
        batch_op.drop_index('ix_program_versions_prog_current')
        batch_op.drop_index(batch_op.f('ix_program_versions_is_current'))
        batch_op.drop_index(batch_op.f('ix_program_versions_id'))

    op.drop_table('program_versions')
    with op.batch_alter_table('change_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_change_logs_id'))

    op.drop_table('change_logs')
    with op.batch_alter_table('agent_steps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_steps_run_id'))
        batch_op.drop_index(batch_op.f('ix_agent_steps_id'))

    op.drop_table('agent_steps')
    with op.batch_alter_table('scraped_pages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scraped_pages_id'))

    op.drop_table('scraped_pages')
    with op.batch_alter_table('programs', schema=None) as batch_op:
        batch_op.drop_index('ix_programs_uni_name_degree')
        batch_op.drop_index(batch_op.f('ix_programs_id'))
        batch_op.drop_index(batch_op.f('ix_programs_content_hash'))

    op.drop_table('programs')
    with op.batch_alter_table('agent_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_runs_university_id'))
        batch_op.drop_index(batch_op.f('ix_agent_runs_id'))

    op.drop_table('agent_runs')
    with op.batch_alter_table('universities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_universities_id'))

    op.drop_table('universities')
    # ### end Alembic commands ###
